### ISSUE TITLE
`zenutils-1.19.0-pre3` server errors

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ZenUtils#57]
Im continue testing alpha releases. Today I launched `zenutils-1.19.0-pre3` **on the dedicated server**.

-----

First error i get is this code:
```ts
strList.add(`${'0'.repeat(24 - toString(cost).length())}${cost};${itemID};${meta}`);
```

```ruby

[ERROR] do/acquire/info.zs:36 > string value has no such member: repeat

```
1. Server running on Java8
2. This error doesn't happened for me on Java22 or Java8 client.

This error could be actually unrelated to ZenUtils since its could be other addon.

-----

Other error related to file, mentioned in other issue: https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/mods/treetweaker.zs

```ruby
[PREINITIALIZATION][SERVER][TRACE] [preinit | SIDE_SERVER]: Loading Script: {[0:preinit]: mods/treetweaker.zs}
[PREINITIALIZATION][SERVER][FATAL] [preinit]: Error executing {[0:preinit]: mods/treetweaker.zs}: org/apache/http/client/methods/HttpUriRequest
java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpUriRequest
	at youyihj.zenutils.impl.zenscript.nat.JavaNativeMemberSymbol.<init>(JavaNativeMemberSymbol.java:37)
	at youyihj.zenutils.impl.zenscript.nat.JavaNativeMemberSymbol.of(JavaNativeMemberSymbol.java:54)
	at youyihj.zenutils.impl.zenscript.nat.ZenTypeJavaNative.lambda$getSymbol$1(ZenTypeJavaNative.java:170)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1128)
	at youyihj.zenutils.impl.zenscript.nat.ZenTypeJavaNative.getSymbol(ZenTypeJavaNative.java:170)
	at youyihj.zenutils.impl.zenscript.nat.ZenTypeJavaNative.getMember(ZenTypeJavaNative.java:73)
	at stanhebben.zenscript.expression.partial.PartialLocal.getMember(PartialLocal.java:29)
	at stanhebben.zenscript.parser.expression.ParsedExpressionMember.compile(ParsedExpressionMember.java:25)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:28)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:27)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:19)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:152)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:228)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:96)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:100)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:78)
	at youyihj.zenutils.impl.runtime.ZenUtilsTweaker.loadScript(ZenUtilsTweaker.java:82)
	at crafttweaker.mc1120.CraftTweaker.onPreInitialization(CraftTweaker.java:167)
```

[crafttweaker.log](https://github.com/user-attachments/files/15787336/crafttweaker.log)
[debug.log](https://github.com/user-attachments/files/15787346/debug.log)

**Comment by friendlyhj** [comment]
`repeat` method is not existent in Java 8. It is added in Java 11. I doesn't believe it work on your java 8 instance.

**Comment by Krutoy242** [comment]
>  I doesn't believe it works on your java 8

Ok, true, i just didnt relized that i saved file with a fix before test Java8. Sorry for missinformation here.

**Comment by GBLodb** [comment]
Could you provide the script about the second error? The one with trouble finding HttpUriRequest?

**Comment by Krutoy242** [comment]
> Could you provide the script about the second error? The one with trouble finding HttpUriRequest?

Its linked in first post https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/scripts/mods/treetweaker.zs
