### ISSUE TITLE
Incompatible with Cleanroom 0.2.3

### ISSUE THREAD

**Issue by Krutoy242** [friendlyhj/ZenUtils#65]
```ruby
java.lang.NoSuchMethodError: 'org.spongepowered.asm.mixin.extensibility.IMixinProcessor org.spongepowered.asm.mixin.transformer.IMixinTransformer.getProcessor()'
    at youyihj.zenutils.impl.zenscript.mixin.ZenMixin.load(ZenMixin.java:52)
    at net.minecraftforge.fml.common.LoadController.handler$bed000$unknown_owner$beforeConstructing(MixinCleanroomLoadController.java:1022)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(MixinCleanroomLoadController.java:217)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:600)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
```

[debug.log](https://github.com/user-attachments/files/16848072/debug.log)

[crash-2024-09-03_14.47.54-client.txt](https://github.com/user-attachments/files/16848099/crash-2024-09-03_14.47.54-client.txt)

**Comment by friendlyhj** [comment]
Should fixed in `v1.20.1`

**Comment by Krutoy242** [comment]
Updating to `1.20.1` wont help

```ruby
java.lang.ClassCastException: class org.spongepowered.asm.mixin.transformer.MixinProcessor cannot be cast to class org.spongepowered.asm.mixin.extensibility.IMixinProcessor (org.spongepowered.asm.mixin.transformer.MixinProcessor and org.spongepowered.asm.mixin.extensibility.IMixinProcessor are in unnamed module of loader net.minecraft.launchwrapper.LaunchClassLoader @28194a50)
    at youyihj.zenutils.impl.zenscript.mixin.ZenMixin.load(ZenMixin.java:54)
    at net.minecraftforge.fml.common.LoadController.handler$bed000$unknown_owner$beforeConstructing(MixinCleanroomLoadController.java:1022)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(MixinCleanroomLoadController.java:217)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:600)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
    at net.minecraft.client.Minecraft.init(MinecraftAccessor.java:467)
    at net.minecraft.client.Minecraft.run(MinecraftAccessor.java:6586)
    ```

[debug.log](https://github.com/user-attachments/files/16868134/debug.log)

**Comment by Krutoy242** [comment]
Also, when kept `v1.20.1` version and changed branch back to main (without your mixin PR) i got this error in CT.log:
```ruby
[PREINITIALIZATION][CLIENT][TRACE] [preinit | SIDE_CLIENT]: Loading Script: {[0:preinit]: mods\treetweaker.zs}
[PREINITIALIZATION][CLIENT][FATAL] [preinit]: Error executing {[0:preinit]: mods\treetweaker.zs}: null
java.nio.file.ClosedFileSystemException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(Unknown Source)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.exists(Unknown Source)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.exists(Unknown Source)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.exists(Unknown Source)
	at java.base/java.nio.file.Files.exists(Unknown Source)
	at youyihj.zenutils.impl.member.bytecode.BytecodeClassDataFetcher.findClass(BytecodeClassDataFetcher.java:108)
	at youyihj.zenutils.impl.member.bytecode.BytecodeClassDataFetcher.forName(BytecodeClassDataFetcher.java:60)
	at youyihj.zenutils.impl.member.bytecode.BytecodeClassDataFetcher.type(BytecodeClassDataFetcher.java:89)
	at youyihj.zenutils.impl.member.bytecode.BytecodeMethodData.parameters(BytecodeMethodData.java:67)
	at youyihj.zenutils.impl.zenscript.nat.NativeMethod.<init>(NativeMethod.java:31)
	at youyihj.zenutils.impl.zenscript.nat.JavaNativeMemberSymbol.lambda$new$1(JavaNativeMemberSymbol.java:42)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at youyihj.zenutils.impl.zenscript.nat.JavaNativeMemberSymbol.<init>(JavaNativeMemberSymbol.java:43)
	at youyihj.zenutils.impl.zenscript.nat.JavaNativeMemberSymbol.of(JavaNativeMemberSymbol.java:57)
	at youyihj.zenutils.impl.zenscript.nat.ZenTypeJavaNative.lambda$getSymbol$2(ZenTypeJavaNative.java:212)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at youyihj.zenutils.impl.zenscript.nat.ZenTypeJavaNative.getSymbol(ZenTypeJavaNative.java:212)
	at youyihj.zenutils.impl.zenscript.nat.ZenTypeJavaNative.getMember(ZenTypeJavaNative.java:100)
	at stanhebben.zenscript.expression.partial.PartialLocal.getMember(PartialLocal.java:29)
	at stanhebben.zenscript.parser.expression.ParsedExpressionMember.compile(ParsedExpressionMember.java:25)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:28)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:27)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:19)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:152)
	at crafttweaker.runtime.CrTTweaker.loadScript(MixinCrTTweaker.java:228)
	at crafttweaker.runtime.CrTTweaker.loadScript(MixinCrTTweaker.java:96)
	at crafttweaker.runtime.CrTTweaker.loadScript(MixinCrTTweaker.java:100)
	at crafttweaker.runtime.CrTTweaker.loadScript(MixinCrTTweaker.java:78)
	at youyihj.zenutils.impl.runtime.ZenUtilsTweaker.loadScript(ZenUtilsTweaker.java:96)
	at crafttweaker.mc1120.CraftTweaker.onPreInitialization(MixinCraftTweaker.java:167)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:303)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:281)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:85)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:142)
	at com.google.common.eventbus.Subscriber.lambda$dispatchEvent$0(Subscriber.java:71)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:68)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:111)
	at com.google.common.eventbus.EventBus.post(EventBus.java:270)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:217)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:634)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:251)
	at net.minecraft.client.Minecraft.func_71384_a(MinecraftAccessor.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftAccessor.java:6586)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at top.outlands.foundation.boot.Foundation.main(Foundation.java:41)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by friendlyhj** [comment]
[zenutils-1.20.1.zip](https://github.com/user-attachments/files/16868866/zenutils-1.20.1.zip)
Try this? Due to github upload limit, please rename the file extension to jar.

**Comment by Krutoy242** [comment]
> [zenutils-1.20.1.zip](https://github.com/user-attachments/files/16868866/zenutils-1.20.1.zip) Try this? Due to github upload limit, please rename the file extension to jar.

Fatal error fixed, but i didnt test mixins yet.

**Comment by Krutoy242** [comment]
Tested with mixins. MC is loading fine, can see this lines in CT.log:
```ruby
[CONSTRUCTING][CLIENT][TRACE] [mixin | SIDE_CLIENT]: Loading Script: {[0:mixin]: mixins\actuallyadditions.zs}
```

**Comment by friendlyhj** [comment]
[zenutils-1.20.2.zip](https://github.com/user-attachments/files/16872576/zenutils-1.20.2.zip)

**Comment by Krutoy242** [comment]
I will try later

**Comment by Krutoy242** [comment]
Tested. Now its working. No errors and mixins actually applied.
