### ISSUE TITLE
ClassCastException during early stage of launch

### ISSUE THREAD

**Issue by ZZZank** [friendlyhj/ZenUtils#73]
using ZenUtils 1.20.10, the newest avaliable currently

[latest.log](https://github.com/user-attachments/files/17396376/latest.log)

```log
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ZenUtils (zenutils)
Caused by: java.lang.ClassCastException: class crafttweaker.api.logger.MTLogger cannot be cast to class youyihj.zenutils.impl.runtime.ZenUtilsLogger (crafttweaker.api.logger.MTLogger and youyihj.zenutils.impl.runtime.ZenUtilsLogger are in unnamed module of loader net.minecraft.launchwrapper.LaunchClassLoader @7283d3eb)
    at youyihj.zenutils.ZenUtils.onConstruct(ZenUtils.java:53)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
...
```

**Comment by friendlyhj** [comment]
#82
