### ISSUE TITLE
Encountered LoaderExceptionModCrash

### ISSUE THREAD

**Issue by tttsaurus** [friendlyhj/ZenUtils#82]
https://mclo.gs/Wm3Vf2Z
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ZenUtils (zenutils)
	Caused by: java.lang.IllegalStateException: CraftTweaker ITweaker or Logger is not redirected. A mixin config is failed. please report to the mod author!
	    at youyihj.zenutils.ZenUtils.onConstruct(ZenUtils.java:59)
	    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	    at java.lang.reflect.Method.invoke(Method.java:580)
	    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
	    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	    at java.lang.reflect.Method.invoke(Method.java:580)
```

*Environment*:
- zenutils 1.21.4
- prism launcher
- cleanroom mmc instance 0.2.4-a
- fugue 0.17.1
- loliasm 5.20

could be caused by other mods' incompat tho

**Comment by friendlyhj** [comment]
please upload latest.log

**Comment by tttsaurus** [comment]
i just reproduced that crash

https://mclo.gs/zX428pE
[latest.zip](https://github.com/user-attachments/files/18017069/latest.zip)

and fortunately, i found the mod (which is one im working on) that triggers the crash

however, everthing works fine under cleanroom-0.2.3 with the same setup
when it comes to cleanroom-0.2.4, it's broken

btw, im really not sure if it was a zenutils issue although the crash report says `at youyihj.zenutils.impl.zenscript.mixin.ZenMixin.load(ZenMixin.java:43)`

**Comment by friendlyhj** [comment]
The issue is same as #73. It is because mixinbooter didn't load my mixin.

**Comment by friendlyhj** [comment]
In my test instance in cleanroom 0.2.4, my mod can work with your mod. It is a random issue. :(

**Comment by tttsaurus** [comment]
so i guess ill wait for the [#73](https://github.com/friendlyhj/ZenUtils/issues/73) fix

**Comment by friendlyhj** [comment]
A mixin from other mod is broken and stlos mixin booter from loading remaining mixins. The latest cleanroom build should fix it.
